apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: traefik
spec:
  authentication:
    kubernetesAuth:
      identityId: "$(INFISICAL_IDENTITY_ID)"
      secretsScope:
        envSlug: development
        secretsPath: "/Traefik"
