apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
  namespace: traefik
spec:
  secretName: wildcard-certificate
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  commonName: '*.${DOMAIN}'
  dnsNames:
    - '*.${DOMAIN}'
    - '${DOMAIN}'
