apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  authentication:
    kubernetesAuth:
      identityId: "$(INFISICAL_IDENTITY_ID)"
      secretsScope:
        envSlug: prod
        secretsPath: "/Cert-Manager"
