apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nfs-volumes.yaml
  - cloud-nfs-volumes.yaml
  - nfs-storageclass.yaml
  - media-pvcs.yaml
  - cloud-pvcs.yaml
  - paperless-nfs-volumes.yaml
  - paperless-pvcs.yaml
