apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tracearr-ingress
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tracearr.${DOMAIN}`)
      kind: Rule
      services:
        - name: tracearr
          port: 3000
