apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: teslamate-ingress
  namespace: productivity
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`teslamate.${DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      services:
        - name: authentik-server
          namespace: auth
          port: http
    - match: Host(`teslamate.${DOMAIN}`)
      kind: Rule
      services:
        - name: teslamate
          port: 4000
      middlewares:
        - name: authentik
          namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: teslamate-grafana-ingress
  namespace: productivity
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`teslamate-grafana.${DOMAIN}`)
      kind: Rule
      services:
        - name: teslamate-grafana
          port: 3000
