apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database.yaml
  - pvc.yaml
  - mosquitto-configmap.yaml
  - infisical-secret.yaml
  - release-mosquitto.yaml
  - release-teslamate.yaml
  - release-grafana.yaml
  - ingress.yaml
