apiVersion: v1
kind: ConfigMap
metadata:
  name: teslamate-mosquitto-config
  namespace: productivity
data:
  mosquitto-no-auth.conf: |
    listener 1883
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/
