apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: traefik
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "$(INFISICAL_IDENTITY_ID)"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "$(INFISICAL_PROJECT_ID)"
        envSlug: ENV
        secretsPath: "/Traefik"
  managedKubeSecretReferences:
    - secretName: cloudflare-api-token-secret
      secretNamespace: traefik
      creationPolicy: Owner
      template:
        includeAllSecrets: true
