apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: speedtest-tracker-ingress
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`speedtest.${DOMAIN}`)
      kind: Rule
      services:
        - name: speedtest-tracker
          port: 80
