apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: collabora-ingress
  namespace: nextcloud
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`office.${DOMAIN}`)
      kind: Rule
      services:
        - name: collabora
          port: 9980
