apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-ingress
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyfin.${DOMAIN}`)
      kind: Rule
      services:
        - name: jellyfin-external
          port: 8096
