apiVersion: v1
kind: Service
metadata:
  name: jellyfin-external
  namespace: media
spec:
  type: ExternalName
  externalName: nas.local.zech.co
  ports:
    - name: http
      port: 8096
      targetPort: 8096
