apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: karakeep-ingress
  namespace: productivity
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`karakeep.${DOMAIN}`)
      kind: Rule
      services:
        - name: karakeep
          port: 3000
