apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - infisical-secret.yaml
  - release-chrome.yaml
  - release-meilisearch.yaml
  - release.yaml
  - ingress.yaml
