apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: freshrss-ingress
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`freshrss.${DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      services:
        - name: authentik-server
          namespace: auth
          port: http
    - match: Host(`freshrss.${DOMAIN}`)
      kind: Rule
      services:
        - name: freshrss
          port: 80
      middlewares:
        - name: authentik
          namespace: traefik
