apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: freshrss-ingress
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rss.${DOMAIN}`)
      kind: Rule
      services:
        - name: freshrss
          port: 80
