apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud-ingress
  namespace: cloud
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cloud.${DOMAIN}`)
      kind: Rule
      middlewares:
        - name: nextcloud-security-headers
      services:
        - name: nextcloud
          port: 8080
