apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infisical-secret.yaml
  - database.yaml
  - pvc.yaml
  - release.yaml
  - security-headers-middleware.yaml
  - well-known-redirects-middleware.yaml
  - ingress.yaml
