apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s-repository-automation.yaml
  - bjw-s-repository-health.yaml
  - bjw-s-repository-media.yaml
  - bjw-s-repository-productivity.yaml
  - bjw-s-repository-unifi.yaml
  - authentik-repository.yaml
  - cert-manager-repository.yaml
  - cnpg-repository.yaml
  - infisical-repository.yaml
  - metallb-repository.yaml
  - proxmox-csi-repository.yaml
  - traefik-repository.yaml
