apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik-repository.yaml
  - cert-manager-repository.yaml
  - cnpg-repository.yaml
  - external-secrets-repository.yaml
  - metallb-repository.yaml
  - proxmox-csi-repository.yaml
  - traefik-repository.yaml
