apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../authentik/base
  - ../sonarr/base
  - ../radarr/base
  - ../sabnzbd/base
  - ../prowlarr/base
  - ../bazarr/base
  - ../jellyseerr/base
  - ../jellystat/base
  - ../unifi-network-application/base
