apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../authentik/base
  - ../freshrss/base
  - ../sonarr/base
  - ../radarr/base
  - ../sabnzbd/base
  - ../prowlarr/base
  - ../bazarr/base
  - ../jellyseerr/base
  - ../jellyfin/base
  - ../jellystat/base
  - ../unifi-network-application/base
  - ../karakeep/base
  - ../bentopdf/base
  - ../teslamate/base
  - ../paperless/base
  - ../it-tools/base
  - ../speedtest-tracker/base
  - ../n8n/base
  - ../norish/base
  - ../healthchecks/base
