apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellystat-ingress
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellystat.${DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      services:
        - name: authentik-server
          namespace: auth
          port: http
    - match: Host(`jellystat.${DOMAIN}`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: jellystat
          port: 3000
    - match: Host(`jellystat.${DOMAIN}`)
      kind: Rule
      services:
        - name: jellystat
          port: 3000
      middlewares:
        - name: authentik
          namespace: traefik
