apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-ingress
  namespace: productivity
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`paperless.${DOMAIN}`)
      kind: Rule
      services:
        - name: paperless
          port: 8000
