apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-ingress
  namespace: productivity
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`paperless.${DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      services:
        - name: authentik-server
          namespace: auth
          port: http
    - match: Host(`paperless.${DOMAIN}`)
      kind: Rule
      services:
        - name: paperless
          port: 8000
      middlewares:
        - name: authentik
          namespace: traefik
