apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infisical-secret.yaml
  - database.yaml
  - pvc.yaml
  - release-redis.yaml
  - release-gotenberg.yaml
  - release-tika.yaml
  - release-paperless.yaml
  - ingress.yaml
