apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth-limits.yaml
  - automation-limits.yaml
  - cnpg-system-limits.yaml
  - health-limits.yaml
  - media-limits.yaml
  - monitoring-limits.yaml
  - productivity-limits.yaml
  - unifi-limits.yaml
