apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-ingress
  namespace: immich
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`photos.${DOMAIN}`)
      kind: Rule
      services:
        - name: immich-server
          port: 2283
