apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: changedetection-ingress
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`change.${DOMAIN}`)
      kind: Rule
      services:
        - name: changedetection
          port: 5000
