apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: norish-ingress
  namespace: health
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`norish.${DOMAIN}`)
      kind: Rule
      services:
        - name: norish
          port: 3000
