apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infisical-secret.yaml
  - database.yaml
  - pvc.yaml
  - release-redis.yaml
  - release-chrome-headless.yaml
  - release.yaml
  - ingress.yaml
