apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seerr-ingress
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`seerr.${DOMAIN}`)
      kind: Rule
      services:
        - name: seerr
          port: 5055
