apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bentopdf-ingress
  namespace: productivity
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pdf.${DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      services:
        - name: authentik-server
          namespace: auth
          port: http
    - match: Host(`pdf.${DOMAIN}`)
      kind: Rule
      services:
        - name: bentopdf
          port: 8080
      middlewares:
        - name: authentik
          namespace: traefik
