---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: unifi-network-application-transport
  namespace: unifi
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unifi-network-application-ingress
  namespace: unifi
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unifi.${DOMAIN}`)
      kind: Rule
      services:
        - name: unifi-network-application
          port: 8443
          scheme: https
          serversTransport: unifi-network-application-transport
