apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - mongodb-init-configmap.yaml
  - ingress.yaml
  - infisical-secret.yaml
  - mongodb-release.yaml
  - release.yaml
