apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: healthchecks-ingress
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`healthchecks.${DOMAIN}`)
      kind: Rule
      services:
        - name: healthchecks
          port: 8000
