apiVersion: v1
kind: ConfigMap
metadata:
  name: proxmox-ca
  namespace: csi-proxmox
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIICpzCCAk2gAwIBAgIBADAKBggqhkjOPQQDAjCBjDELMAkGA1UEBhMCQVQxEzAR
    BgNVBAgMClZvcmFybGJlcmcxEDAOBgNVBAcMB1Nvbm50YWcxEDAOBgNVBAoMB0hv
    bWVsYWIxCzAJBgNVBAsMAklUMR0wGwYJKoZIhvcNAQkBFg5hZHJpYW5AemVjaC5j
    bzEYMBYGA1UEAwwPSG9tZWxhYiBSb290IENBMB4XDTI2MDIwNTE2NDA0NFoXDTM2
    MDIwMzE2NDA0NFowgYwxCzAJBgNVBAYTAkFUMRMwEQYDVQQIDApWb3JhcmxiZXJn
    MRAwDgYDVQQHDAdTb25udGFnMRAwDgYDVQQKDAdIb21lbGFiMQswCQYDVQQLDAJJ
    VDEdMBsGCSqGSIb3DQEJARYOYWRyaWFuQHplY2guY28xGDAWBgNVBAMMD0hvbWVs
    YWIgUm9vdCBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABB3Z3ZVzNXQaNpFM
    ubbRqqw6Zj+lCWGjV5ohiDXKgjRLJR5WCefL8C514pHZRRGF2HvOrbhPSVMXm6WQ
    +XXk5kmjgZ0wgZowNwYJYIZIAYb4QgENBCoWKE9QTnNlbnNlIEdlbmVyYXRlZCBD
    ZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHQYDVR0OBBYEFMdDWYmcoCkz9BQiUtqFUHT+
    lJb2MB8GA1UdIwQYMBaAFMdDWYmcoCkz9BQiUtqFUHT+lJb2MA8GA1UdEwEB/wQF
    MAMBAf8wDgYDVR0PAQH/BAQDAgGGMAoGCCqGSM49BAMCA0gAMEUCIQDBv9ASkSvu
    DcoAIFH2bwn1shUp1yifKqb6V5TA9AIEvAIgUDLKRR4ebJSZrc/UnCoQbmEvRnA9
    8UBoHsy9tpGIsLk=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIICqTCCAlCgAwIBAgIBATAKBggqhkjOPQQDAjCBjDELMAkGA1UEBhMCQVQxEzAR
    BgNVBAgMClZvcmFybGJlcmcxEDAOBgNVBAcMB1Nvbm50YWcxEDAOBgNVBAoMB0hv
    bWVsYWIxCzAJBgNVBAsMAklUMR0wGwYJKoZIhvcNAQkBFg5hZHJpYW5AemVjaC5j
    bzEYMBYGA1UEAwwPSG9tZWxhYiBSb290IENBMB4XDTI2MDIwNTE2NDIyOVoXDTMx
    MDIwNDE2NDIyOVowgY8xCzAJBgNVBAYTAkFUMRMwEQYDVQQIDApWb3JhcmxiZXJn
    MRAwDgYDVQQHDAdTb25udGFnMRAwDgYDVQQKDAdIb21lbGFiMQswCQYDVQQLDAJJ
    VDEdMBsGCSqGSIb3DQEJARYOYWRyaWFuQHplY2guY28xGzAZBgNVBAMMEkhvbWVs
    YWIgSXNzdWluZyBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFyN7j9XuZsT
    jN81BFuzUDKTKRxwU91vzx9Hh0qEip13cNAiQGH2KWDJw5rsqj5wpDlh70/6gyS+
    HAImiWBlW32jgZ0wgZowNwYJYIZIAYb4QgENBCoWKE9QTnNlbnNlIEdlbmVyYXRl
    ZCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHQYDVR0OBBYEFFq/cTU1j4n9ws+N8oq3
    ebmEFX+yMB8GA1UdIwQYMBaAFMdDWYmcoCkz9BQiUtqFUHT+lJb2MA8GA1UdEwEB
    /wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMAoGCCqGSM49BAMCA0cAMEQCIDHVc/W5
    3pxiFC9+W4wYJlkCZ8mb5hlTBRFqGHgMF9qzAiBhesNSPMalPb3bQb6VPCkgrJ8j
    uIsdDSLy8GPy9EOGng==
    -----END CERTIFICATE-----
